const Events = [
  {
    title: "Rock Music Fest 2025",
    description:
      "Join us for an electrifying night with top bands from around the world. Food and drinks included!",
    date: "2025-08-15",
    location: "Indira Gandhi Indoor Stadium, Delhi",
    price: 799,
    maxTickets: 5000,
    ticketsSold: 0,
    category: "Music",
    image: "https://cdn.example.com/events/rockfest.jpg",
    organizer: "648a3a64fc13ae08423e654a",
  },
  {
    title: "Tech Conference 2025",
    description:
      "Network with tech leaders, attend insightful sessions and explore startups.",
    date: "2025-09-12",
    location: "BIEC, Bangalore",
    price: 1199,
    maxTickets: 3000,
    ticketsSold: 0,
    category: "Technology",
    image: "https://cdn.example.com/events/techconf.jpg",
    organizer: "648a3a64fc13ae08423e654a",
  },
  {
    title: "Food Carnival",
    description:
      "Taste delicious cuisines from around the world, live music and games.",
    date: "2025-10-05",
    location: "Marine Drive, Mumbai",
    price: 299,
    maxTickets: 10000,
    ticketsSold: 0,
    category: "Food",
    image: "https://cdn.example.com/events/foodfest.jpg",
    organizer: "648a3a64fc13ae08423e654a",
  },
  {
    title: "Startup Expo 2025",
    description:
      "Meet investors, pitch ideas and explore latest innovations in startups.",
    date: "2025-11-20",
    location: "Pragati Maidan, Delhi",
    price: 499,
    maxTickets: 6000,
    ticketsSold: 0,
    category: "Business",
    image: "https://cdn.example.com/events/startupexpo.jpg",
    organizer: "648a3a64fc13ae08423e654a",
  },
  {
    title: "Marathon 2025",
    description: "Join the largest marathon of India and test your endurance.",
    date: "2025-12-10",
    location: "Cubbon Park, Bangalore",
    price: 199,
    maxTickets: 15000,
    ticketsSold: 0,
    category: "Sports",
    image: "https://cdn.example.com/events/marathon.jpg",
    organizer: "648a3a64fc13ae08423e654a",
  },
  {
    title: "Comedy Night Live",
    description:
      "An evening full of laughter with India's top standup comedians.",
    date: "2025-09-25",
    location: "JLN Stadium, Delhi",
    price: 499,
    maxTickets: 4000,
    ticketsSold: 0,
    category: "Comedy",
    image: "https://cdn.example.com/events/comedy.jpg",
    organizer: "648a3a64fc13ae08423e654a",
  },
  {
    title: "International Jazz Festival",
    description: "Groove to the soulful sounds of world-famous jazz artists.",
    date: "2025-10-15",
    location: "Gateway of India, Mumbai",
    price: 899,
    maxTickets: 3500,
    ticketsSold: 0,
    category: "Music",
    image: "https://cdn.example.com/events/jazzfest.jpg",
    organizer: "648a3a64fc13ae08423e654a",
  },
  {
    title: "Art & Craft Expo",
    description: "Discover traditional and modern art exhibits and workshops.",
    date: "2025-11-08",
    location: "Kala Academy, Goa",
    price: 150,
    maxTickets: 5000,
    ticketsSold: 0,
    category: "Art",
    image: "https://cdn.example.com/events/artcraft.jpg",
    organizer: "648a3a64fc13ae08423e654a",
  },
  {
    title: "Startup Pitch Day",
    description: "Watch top startups pitch live to investors and accelerators.",
    date: "2025-11-20",
    location: "T-Hub, Hyderabad",
    price: 399,
    maxTickets: 2500,
    ticketsSold: 0,
    category: "Business",
    image: "https://cdn.example.com/events/startup-pitch.jpg",
    organizer: "648a3a64fc13ae08423e654a",
  },
  {
    title: "Kids Carnival",
    description:
      "Fun rides, games, food stalls and magic shows for kids and families.",
    date: "2025-12-05",
    location: "Wonderla, Bangalore",
    price: 299,
    maxTickets: 8000,
    ticketsSold: 0,
    category: "Kids",
    image: "https://cdn.example.com/events/kids-carnival.jpg",
    organizer: "648a3a64fc13ae08423e654a",
  },
  {
    title: "Literature Fest",
    description:
      "Meet your favorite authors, attend poetry slams and book readings.",
    date: "2026-01-10",
    location: "JLF Grounds, Jaipur",
    price: 199,
    maxTickets: 6000,
    ticketsSold: 0,
    category: "Literature",
    image: "https://cdn.example.com/events/litfest.jpg",
    organizer: "648a3a64fc13ae08423e654a",
  },
  {
    title: "Yoga & Wellness Retreat",
    description:
      "Rejuvenate your mind and body with guided meditation and yoga sessions.",
    date: "2026-02-15",
    location: "Isha Center, Coimbatore",
    price: 999,
    maxTickets: 2000,
    ticketsSold: 0,
    category: "Health",
    image: "https://cdn.example.com/events/yoga-retreat.jpg",
    organizer: "648a3a64fc13ae08423e654a",
  },
  {
    title: "MotoGP Championship",
    description:
      "Watch top racers from around the world compete at blistering speeds.",
    date: "2026-03-22",
    location: "BIC, Greater Noida",
    price: 1299,
    maxTickets: 15000,
    ticketsSold: 0,
    category: "Sports",
    image: "https://cdn.example.com/events/motogp.jpg",
    organizer: "648a3a64fc13ae08423e654a",
  },
];

module.exports = Events;
